### ISSUE TITLE
Error on initialize

### ISSUE THREAD

**Issue by TittoProof** [fiware-cybercaptor/cybercaptor-server#6]
hi, this error after visit link http://localhost:8080/cybercaptor-server-4.4.3/rest/json/initialize

{"error":"the attack graph is empty"}

I use MacOsx and i notice that there is no config.properties under configuration-file folder

thanks

**Comment by TittoProof** [comment]
here the stack trace:

 org.fiware.cybercaptor.server.rest.RestJsonAPI initialise
Informazioni: Generating topology and mulval inputs null
java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at org.fiware.cybercaptor.server.api.InformationSystemManagement.prepareMulVALInputs(InformationSystemManagement.java:251)
    at org.fiware.cybercaptor.server.rest.RestJsonAPI.initialise(RestJsonAPI.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)

**Comment by fxaguessy** [comment]
Hello,

This application can not be launched on Mac OS X, as  MuLVAL can not be built on such platform. This application is Linux Only.
Moreover, we need to update the documentation to explain how to write a proper config.properties file.

However, if you want to try CyberCAPTOR, the easiest way is to use the Docker container that is configured to work "out of the box" (for example, the config.properties is already written). Docker can be easily installed on Mac OS X : https://docs.docker.com/installation/mac/.

**Comment by TittoProof** [comment]
many thanks! i'll try this way!
